---
# Role tasks

- name: assert platform is supported
  assert:
    that:
      - distribution in files_supported_distributions
      - >-
        ansible_facts.distribution_version
        is version(files_supported_versions[distribution], ">=")
  vars:
    distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::files
    - role::files::check

- name: setup files
  file:
    attributes: "{{ item.attributes | default(omit) }}"
    follow: "{{ item.follow | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    recurse: "{{ item.recurse | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
  loop: "{{ files }}"
  loop_control:
    label: "{{ item.path }}"
  tags:
    - role::files
