---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check files
      ansible.builtin.stat:
        path: "{{ files_prefix }}/{{ item }}"
      loop: "{{ (files + files_extra) | map(attribute='path') | list }}"
      register: check_result

    - name: Check file contents
      ansible.builtin.command: cat /tmp/testfile
      changed_when: no
      register: check_content

    - name: Check files are correct
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - check_content.stdout == "Hello World"
        quiet: yes
      loop: "{{ check_result.results }}"
      loop_control:
        label: "{{ item.stat.path }}"
